//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<int> IdViewAnimal { get; set; }
        public string Nickname { get; set; }
        public Nullable<bool> Pasport { get; set; }
        public Nullable<int> Age { get; set; }
        public string Service { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual ViewAnimal ViewAnimal { get; set; }
    }
}
